/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplikasi;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author Cab Priok
 */
public class FormBooking extends javax.swing.JFrame {
String id;
String tglmain;
String jammain;
String lapangan;
String durasi;
DefaultTableModel tabMode;
Connection koneksi;
    /**
     * Creates new form FormBooking
     */
    public FormBooking() {
        initComponents();
        Object[] row= {"ID Anggota","Tgl Main", "Jam Main", "Lapangan", "Durasi"};
        tabeldata.setModel(tabMode);
        tglskrg();
    }

    public void tglskrg(){
Date skrg= new Date();
SimpleDateFormat format= new SimpleDateFormat("dd-MM-yyyy");
String tgl = format.format(skrg);
tftanggal.setText(format.format(skrg));
}
    public void konekdatabase(){
try{
Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
koneksi =DriverManager.getConnection("jdbc:mysql://localhost:3306/bookinglapfutsal","root","");
}
catch (Exception e)
{
System.err.println("Exception: "+e.getMessage());
}
}
     public void hapustabel(){
int row=tabMode.getRowCount();
for(int i=0;i<row;i++){
tabMode.removeRow(0);
}
     }
     
public void tampildataketabel(){
hapustabel();
try{
String sql="Select * from parkirmasuk";
Statement stat=koneksi.createStatement();
ResultSet set=stat.executeQuery(sql);
while (set.next()){
id=set.getString("ID Anggota");
tglmain=set.getString("Tgl Main");
jammain=set.getString("Jam Main");
lapangan=set.getString("Lapangan");
durasi=set.getString("Durasi");
String[] data={id,tglmain,jammain,lapangan,durasi};
tabMode.addRow(data);
}
}
catch(Exception e){
}
}  

public void clear(){
ID_ANGGOTA.setText("");
JAM_MAIN.setText("");
DURASI.setText("");
}

     public void simpandata(){
id=ID_ANGGOTA.getText();
tglmain=TGL_MAIN.getText();
jammain=JAM_MAIN.getText();
lapangan=(String)LAPANGAN.getSelectedItem();
durasi=DURASI.getText();
try{
konekdatabase();
Statement statement=koneksi.createStatement();
String sql="insert into parkirmasuk values ('"+id+"','"+tglmain+"','"+jammain+
"','"+lapangan+"','"+durasi+"');";
statement.executeUpdate(sql);
statement.close();
clear();
}
catch (Exception e){
}
}
     
     public void data(){
id=ID_ANGGOTA.getText();
tglmain=TGL_MAIN.getText();
jammain=JAM_MAIN.getText();
lapangan=(String)LAPANGAN.getSelectedItem();
durasi=DURASI.getText();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LABEL_ID_ANGGOTA = new javax.swing.JLabel();
        LABEL_TGL_MAIN = new javax.swing.JLabel();
        LABEL_LAPANGAN = new javax.swing.JLabel();
        LABEL_JAM_MAIN = new javax.swing.JLabel();
        LABEL_DURASI = new javax.swing.JLabel();
        ID_ANGGOTA = new javax.swing.JTextField();
        TGL_MAIN = new javax.swing.JTextField();
        LAPANGAN = new javax.swing.JComboBox<>();
        JAM_MAIN = new javax.swing.JTextField();
        DURASI = new javax.swing.JTextField();
        SIMPAN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        judul.setText("FORM BOOKING");

        LABEL_ID_ANGGOTA.setText("ID");

        LABEL_TGL_MAIN.setText("TANGGAL MAIN");

        LABEL_LAPANGAN.setText("PILIH LAPANGAN");

        LABEL_JAM_MAIN.setText("JAM BERMAIN");

        LABEL_DURASI.setText("DURASI");

        LAPANGAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        jButton2.setText("LANJUT PEMBAYARAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(judul))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LABEL_ID_ANGGOTA)
                                    .addComponent(LABEL_TGL_MAIN)
                                    .addComponent(LABEL_LAPANGAN)
                                    .addComponent(LABEL_JAM_MAIN)
                                    .addComponent(LABEL_DURASI))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TGL_MAIN)
                                    .addComponent(JAM_MAIN)
                                    .addComponent(DURASI)
                                    .addComponent(LAPANGAN, 0, 156, Short.MAX_VALUE)
                                    .addComponent(ID_ANGGOTA))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(SIMPAN)
                                    .addComponent(jButton3))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_ID_ANGGOTA)
                    .addComponent(ID_ANGGOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SIMPAN))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABEL_TGL_MAIN)
                            .addComponent(TGL_MAIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABEL_LAPANGAN)
                            .addComponent(LAPANGAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABEL_JAM_MAIN)
                            .addComponent(JAM_MAIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABEL_DURASI)
                            .addComponent(DURASI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SIMPANActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DURASI;
    private javax.swing.JTextField ID_ANGGOTA;
    private javax.swing.JTextField JAM_MAIN;
    private javax.swing.JLabel LABEL_DURASI;
    private javax.swing.JLabel LABEL_ID_ANGGOTA;
    private javax.swing.JLabel LABEL_JAM_MAIN;
    private javax.swing.JLabel LABEL_LAPANGAN;
    private javax.swing.JLabel LABEL_TGL_MAIN;
    private javax.swing.JComboBox<String> LAPANGAN;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JTextField TGL_MAIN;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel judul;
    // End of variables declaration//GEN-END:variables


}
